class_name Building
extends RefCounted

## Board constants are design inputs, not incidental limits (spec §3).
##
## 40 rows because the board never scrolls VERTICALLY. 8 shafts is a design
## choice rather than a consequence of the screen: an earlier docstring derived
## it from "a 44pt column is ~80.6 units, so ~8.9 fit edge to edge", which
## stopped being a derivation once the shaft strip paged. Five columns are
## visible on a 96-unit pitch and any number could be reachable by paging; eight
## is where the cap sits because past it a building stops reading as one board,
## and a later era could raise it without any geometry changing.

const MAX_ROWS := 40
const MAX_SHAFTS := 8

var row_count: int
var cars: Array[ElevatorCar] = []
var waiting: Array = []          # Array of Array[Passenger], one per row

func _init(p_row_count: int, shaft_count: int) -> void:
	row_count = clampi(p_row_count, 1, MAX_ROWS)
	for i in range(row_count):
		waiting.append([] as Array[Passenger])
	for i in range(clampi(shaft_count, 0, MAX_SHAFTS)):
		cars.append(ElevatorCar.new(0))

func add_shaft() -> bool:
	if cars.size() >= MAX_SHAFTS:
		return false
	cars.append(ElevatorCar.new(0))
	return true

func add_row() -> bool:
	if row_count >= MAX_ROWS:
		return false
	row_count += 1
	waiting.append([] as Array[Passenger])
	return true

func enqueue(p: Passenger) -> void:
	if p.origin_row < 0 or p.origin_row >= row_count:
		return
	waiting[p.origin_row].append(p)

func waiting_at(row: int) -> Array[Passenger]:
	if row < 0 or row >= row_count:
		return [] as Array[Passenger]
	return waiting[row]

func total_waiting() -> int:
	var n := 0
	for queue in waiting:
		n += queue.size()
	return n

## Removes every waiting passenger generated by `source_row`, from EVERY queue.
##
## Source-scoped, not queue-scoped: queues are indexed by origin, so an inbound
## trip belonging to floor F waits at the lobby. Clearing waiting[F] would miss
## all of them, and clearing waiting[0] when the lobby vacates would delete
## every other floor's visitors.
func remove_waiting_from_source(source_row: int) -> int:
	var removed := 0
	for row in range(waiting.size()):
		var survivors: Array[Passenger] = []
		for p in waiting[row]:
			if p.source_row == source_row:
				removed += 1
			else:
				survivors.append(p)
		waiting[row] = survivors
	return removed

## FIFO: the longest-waiting passenger boards first.
func take_boardable(row: int, limit: int) -> Array[Passenger]:
	var out: Array[Passenger] = []
	if limit <= 0 or row < 0 or row >= row_count:
		return out
	var queue: Array[Passenger] = waiting[row]
	var take := mini(limit, queue.size())
	for i in range(take):
		out.append(queue.pop_front())
	return out
