class_name Building
extends RefCounted

## Board constants are design inputs, not incidental limits (spec §3).
##
## 40 floors because the board never scrolls VERTICALLY. 8 shafts is a design
## choice rather than a consequence of the screen: an earlier docstring derived
## it from "a 44pt column is ~80.6 units, so ~8.9 fit edge to edge", which
## stopped being a derivation once the shaft strip paged. Five columns are
## visible on a 96-unit pitch and any number could be reachable by paging; eight
## is where the cap sits because past it a building stops reading as one board,
## and a later era could raise it without any geometry changing.

const MAX_FLOORS := 40
const MAX_SHAFTS := 8

var floor_count: int
var cars: Array[ElevatorCar] = []
var waiting: Array = []          # Array of Array[Passenger], one per floor

func _init(p_floor_count: int, shaft_count: int) -> void:
	floor_count = clampi(p_floor_count, 1, MAX_FLOORS)
	for i in range(floor_count):
		waiting.append([] as Array[Passenger])
	for i in range(clampi(shaft_count, 0, MAX_SHAFTS)):
		cars.append(ElevatorCar.new(0))

func add_shaft() -> bool:
	if cars.size() >= MAX_SHAFTS:
		return false
	cars.append(ElevatorCar.new(0))
	return true

func add_floor() -> bool:
	if floor_count >= MAX_FLOORS:
		return false
	floor_count += 1
	waiting.append([] as Array[Passenger])
	return true

func enqueue(p: Passenger) -> void:
	if p.origin_floor < 0 or p.origin_floor >= floor_count:
		return
	waiting[p.origin_floor].append(p)

func waiting_at(floor_index: int) -> Array[Passenger]:
	if floor_index < 0 or floor_index >= floor_count:
		return [] as Array[Passenger]
	return waiting[floor_index]

func total_waiting() -> int:
	var n := 0
	for queue in waiting:
		n += queue.size()
	return n

## Removes every waiting passenger generated by `source_floor`, from EVERY queue.
##
## Source-scoped, not queue-scoped: queues are indexed by origin, so an inbound
## trip belonging to floor F waits at the lobby. Clearing waiting[F] would miss
## all of them, and clearing waiting[0] when the lobby vacates would delete
## every other floor's visitors.
func remove_waiting_from_source(source_floor: int) -> int:
	var removed := 0
	for floor_index in range(waiting.size()):
		var survivors: Array[Passenger] = []
		for p in waiting[floor_index]:
			if p.source_floor == source_floor:
				removed += 1
			else:
				survivors.append(p)
		waiting[floor_index] = survivors
	return removed

## FIFO: the longest-waiting passenger boards first.
func take_boardable(floor_index: int, limit: int) -> Array[Passenger]:
	var out: Array[Passenger] = []
	if limit <= 0 or floor_index < 0 or floor_index >= floor_count:
		return out
	var queue: Array[Passenger] = waiting[floor_index]
	var take := mini(limit, queue.size())
	for i in range(take):
		out.append(queue.pop_front())
	return out
