class_name TenantKind
extends RefCounted

## One leasable tenant type. `rate` is trips per simulated minute generated by
## ONE FLOOR of this kind, one bucket per simulated hour -- the same shape and
## bucketing as the old building-wide curve, so the piecewise-constant property
## the catch-up integrator would rely on is preserved.
##
## `inbound` is the share of that minute's trips running lobby -> here and
## `outbound` the share running here -> lobby; the remainder is interfloor.
## A kind therefore states where its people GO, not only how many there are,
## which is what makes up-peak and down-peak a consequence of who leased
## rather than a mechanic bolted on.

const BUCKETS := 24

var id: String
var display_name: String
var requires_class: int
var lease_cost: float
var base_fare: float
var rate: PackedFloat32Array
var inbound: PackedFloat32Array
var outbound: PackedFloat32Array

func rate_at(minute: int) -> float:
	return rate[posmod(minute, BUCKETS)]

func inbound_at(minute: int) -> float:
	return inbound[posmod(minute, BUCKETS)]

func outbound_at(minute: int) -> float:
	return outbound[posmod(minute, BUCKETS)]

func interfloor_at(minute: int) -> float:
	return maxf(1.0 - inbound_at(minute) - outbound_at(minute), 0.0)
